// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.AspNetCore.Identity;

namespace Hospitel_Project.Models
{
    public class ApplicationUser:IdentityUser
    {
        public string FullName { get; set; }
      
            public string? Name { get; set; }  // اسم المستخدم بعد الترقية
            public int? DoctorId { get; set; } // ربطه بجدول الأطباء
            public int? PatientId { get; set; } // ربطه بجدول المرضى
        


    }
}