// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Hospitel_Project.Models;

public partial class Diagnosis
{
    [Key]
    public int DiagnoseId { get; set; }

    [Required]
    [StringLength(100)]
    public string Name { get; set; }

    [StringLength(255)]
    public string Comments { get; set; }

    public int PatientId { get; set; }

    [ForeignKey("PatientId")]
    [InverseProperty("Diagnoses")]
    public virtual Patient Patient { get; set; }
}