// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Hospitel_Project.Models;

[Table("Doctor")]
public partial class Doctor
{
    [Key]
    public int DoctorId { get; set; }

    [Required]
    [StringLength(100)]
    public string Name { get; set; }

    public string Email { get; set; }

    [Required]
    [StringLength(100)]
    public string Specialty { get; set; }
    [InverseProperty("AssignedDoctor")]
    public virtual ICollection<Patient> Patients { get; set; } = new List<Patient>();

    [InverseProperty("Doctor")]
    public virtual ICollection<Visitation> Visitations { get; set; } = new List<Visitation>();
}