//// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
//#nullable disable
//using System;
//using System.Collections.Generic;
//using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
//using Microsoft.EntityFrameworkCore;

//namespace Hospitel_Project.Models;

//public partial class HospitalDBContext : IdentityDbContext<ApplicationUser>
//{
//    public HospitalDBContext(DbContextOptions<HospitalDBContext> options)
//        : base(options)
//    {
//    }

//    public virtual DbSet<Diagnosis> Diagnoses { get; set; }

//    public virtual DbSet<Doctor> Doctors { get; set; }

//    public virtual DbSet<Medicament> Medicaments { get; set; }

//    public virtual DbSet<Patient> Patients { get; set; }

//    public virtual DbSet<Visitation> Visitations { get; set; }

//    protected override void OnModelCreating(ModelBuilder modelBuilder)
//    {
//        modelBuilder.Entity<Diagnosis>(entity =>
//        {
//            entity.HasKey(e => e.DiagnoseId).HasName("PK__Diagnose__B5A933FA6DE76CEE");

//            entity.HasOne(d => d.Patient).WithMany(p => p.Diagnoses)
//                .OnDelete(DeleteBehavior.ClientSetNull)
//                .HasConstraintName("FK__Diagnoses__Patie__4222D4EF");
//        });

//        modelBuilder.Entity<Doctor>(entity =>
//        {
//            entity.HasKey(e => e.DoctorId).HasName("PK__Doctor__2DC00EBFC7866D10");
//        });

//        modelBuilder.Entity<Medicament>(entity =>
//        {
//            entity.HasKey(e => e.MedicamentId).HasName("PK__Medicame__0EBA585B5B5FAEA5");
//        });

//        modelBuilder.Entity<Patient>(entity =>
//        {
//            entity.HasKey(e => e.PatientId).HasName("PK__Patients__970EC366D02F1224");

//            entity.HasMany(d => d.Visitations).WithMany(p => p.PatientId)
//                .UsingEntity<Dictionary<string, object>>(
//                    "PatientMedicament",
//                    r => r.HasOne<Medicament>().WithMany()
//                        .HasForeignKey("MedicamentId")
//                        .OnDelete(DeleteBehavior.ClientSetNull)
//                        .HasConstraintName("FK__PatientMe__Medic__47DBAE45"),
//                    l => l.HasOne<Patient>().WithMany()
//                        .HasForeignKey("PatientId")
//                        .OnDelete(DeleteBehavior.ClientSetNull)
//                        .HasConstraintName("FK__PatientMe__Patie__46E78A0C"),
//                    j =>
//                    {
//                        j.HasKey("PatientId", "MedicamentId").HasName("PK__PatientM__37E566E3474F7FE3");
//                        j.ToTable("PatientMedicaments");
//                    });
//        });

//        modelBuilder.Entity<Visitation>(entity =>
//        {
//            entity.HasKey(e => e.VisitationId).HasName("PK__Visitati__66CA28E57F2AE445");

//            entity.Property(e => e.Date).HasDefaultValueSql("(getdate())");

//            entity.HasOne(d => d.Doctor).WithMany(p => p.Visitations)
//                .OnDelete(DeleteBehavior.ClientSetNull)
//                .HasConstraintName("FK__Visitatio__Docto__3E52440B");

//            entity.HasOne(d => d.Patient).WithMany(p => p.Visitations)
//                .OnDelete(DeleteBehavior.ClientSetNull)
//                .HasConstraintName("FK__Visitatio__Patie__3F466844");
//        });

//        OnModelCreatingPartial(modelBuilder);
//    }

//    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
//}