// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Hospitel_Project.Models;

public partial class Medicament
{
    [Key]
    public int MedicamentId { get; set; }

    [Required]
    [StringLength(100)]
    public string Name { get; set; }
    public string TimeOfdosage { get; set; }
    public double price { get; set; }
    public int stock {  get; set; }
    

    public virtual ICollection<PatientMedicament> PatientMedications { get; set; } = new List<PatientMedicament>();
}
