// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Hospitel_Project.Models;

[Index("Email", Name = "UQ__Patients__A9D1053429D2C6FB", IsUnique = true)]
public partial class Patient
{
    [Key]
    public int PatientId { get; set; }

    [Required]
    [StringLength(50)]
    public string FirstName { get; set; }

    [Required]
    [StringLength(50)]
    public string LastName { get; set; }

    [StringLength(255)]
    public string Address { get; set; }

    [StringLength(100)]
    public string Email { get; set; }

    public bool HasInsurance { get; set; }

    public int? AssignedDoctorId { get; set; }

    [ForeignKey("AssignedDoctorId")]
    public virtual Doctor AssignedDoctor { get; set; }

    public virtual ICollection<Diagnosis> Diagnoses { get; set; } = new List<Diagnosis>();

    public virtual ICollection<Visitation> Visitations { get; set; } = new List<Visitation>();

    public virtual ICollection<PatientMedicament> PatientMedications { get; set; } = new List<PatientMedicament>();
}
