// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Hospitel_Project.Models;

public partial class Visitation
{
    [Key]
    public int VisitationId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Date { get; set; }

    [StringLength(255)]
    public string Comments { get; set; }

    public int DoctorId { get; set; }

    public int PatientId { get; set; }

    [ForeignKey("DoctorId")]
    [InverseProperty("Visitations")]
    public virtual Doctor Doctor { get; set; }

    [ForeignKey("PatientId")]
    [InverseProperty("Visitations")]
    public virtual Patient Patient { get; set; }
}